"""Markdown renderers shared across Phase 6 workflows.

Every renderer embeds a stable HTML-comment marker so the corresponding
idempotent upsert helper can locate and update its prior output in place.
"""

from __future__ import annotations

from typing import Any, Iterable

# Marker tokens. Using a single namespace keeps greps trivial.
MARKER_NAMESPACE = "awesome-agentic:phase-6"
LANDSCAPE_MARKER = f"<!-- {MARKER_NAMESPACE}:landscape -->"
NEW_TOOL_MARKER_PREFIX = f"<!-- {MARKER_NAMESPACE}:new-tool:"
REVIEW_MARKER_PREFIX = f"<!-- {MARKER_NAMESPACE}:review:"


def new_tool_marker(url: str) -> str:
    # Use a short stable hash so the marker stays one line.
    import hashlib

    h = hashlib.sha1(url.encode("utf-8")).hexdigest()[:10]
    return f"{NEW_TOOL_MARKER_PREFIX}{h} -->"


def review_marker(pr_number: int) -> str:
    return f"{REVIEW_MARKER_PREFIX}{pr_number} -->"


# ---------------------------------------------------------------------------
# Rubric scorecard (used by new-tool and review-pr)
# ---------------------------------------------------------------------------


def render_scorecard(validation: dict[str, Any]) -> str:
    """Render a ``validate_entry`` / ``triage_pr`` validation dict as a table."""
    if not validation:
        return "_No validation data — the PR body did not contain an entry Markdown block._\n"
    per_raw = validation.get("per_dimension_raw") or {}
    per_w = validation.get("per_dimension") or {}
    lines = [
        "| Dimension | Raw (0-3) | Weighted |",
        "| --- | ---: | ---: |",
    ]
    for name in per_raw:
        lines.append(f"| {name} | {per_raw[name]} | {per_w.get(name, 0)} |")
    total = validation.get("score", 0)
    max_score = validation.get("max_score", 0)
    lines.append(f"| **Total** |  | **{total} / {max_score}** |")
    hits = validation.get("anti_pattern_hits") or []
    gates = validation.get("hard_gate_failures") or []
    tags = validation.get("evidence_tags") or []
    extras: list[str] = []
    if gates:
        extras.append(f"- **Hard-gate failures:** {', '.join(gates)}")
    if hits:
        phrases = ", ".join(f"`{h['phrase']}`" for h in hits)
        extras.append(f"- **Anti-patterns hit:** {phrases}")
    if tags:
        extras.append(f"- **Evidence tags found:** {', '.join(tags)}")
    notes = validation.get("notes") or []
    if notes:
        extras.append("- **Notes:** " + "; ".join(notes))
    body = "\n".join(lines)
    if extras:
        body += "\n\n" + "\n".join(extras)
    return body + "\n"


# ---------------------------------------------------------------------------
# New-tool draft (6.1)
# ---------------------------------------------------------------------------


def render_new_tool_body(*, url: str, section: str, draft_markdown: str, validation: dict[str, Any]) -> str:
    verdict = (validation or {}).get("verdict", "unknown")
    return (
        f"{new_tool_marker(url)}\n"
        f"## Draft entry for `{url}`\n\n"
        f"**Target section:** {section}  \n"
        f"**Automated verdict:** `{verdict}`\n\n"
        "### Proposed Markdown\n\n"
        "```markdown\n"
        f"{draft_markdown}\n"
        "```\n\n"
        "### Rubric scorecard\n\n"
        f"{render_scorecard(validation)}\n"
        "_Generated by the Phase 6 `new-tool` workflow. "
        "This is a draft — human review and a PR are required to merge._\n"
    )


# ---------------------------------------------------------------------------
# Weekly landscape digest (6.2)
# ---------------------------------------------------------------------------


def render_landscape_digest(
    *,
    generated_at: str,
    stale: Iterable[dict[str, Any]],
    candidate_prs: Iterable[dict[str, Any]],
    candidate_issues: Iterable[dict[str, Any]],
) -> str:
    stale = list(stale)
    candidate_prs = list(candidate_prs)
    candidate_issues = list(candidate_issues)

    def _section(title: str, rows: list[str]) -> str:
        if not rows:
            return f"### {title}\n\n_None this week._\n"
        return f"### {title}\n\n" + "\n".join(rows) + "\n"

    stale_rows = [
        f"- `{c['file']}` — "
        + (
            f"last reviewed **{c['last_reviewed']}** ({c['age_months']} months ago)"
            if c.get("reason") == "stale"
            else "**missing `Last reviewed:` marker**"
        )
        for c in stale
    ]
    pr_rows = [
        f"- [#{pr['number']} {pr['title']}]({pr['html_url']}) — merged {pr['merged_at']}"
        for pr in candidate_prs
    ]
    issue_rows = [
        f"- [#{i['number']} {i['title']}]({i['html_url']}) — opened {i['created_at']}"
        for i in candidate_issues
    ]
    return (
        f"{LANDSCAPE_MARKER}\n"
        "# Weekly landscape scan\n\n"
        f"_Generated {generated_at} by the Phase 6 `landscape-scan` workflow. "
        "This issue is updated in place every Monday._\n\n"
        + _section("Stale entries", stale_rows)
        + "\n"
        + _section("Candidate additions from recent PRs", pr_rows)
        + "\n"
        + _section("Candidate additions from recent issues", issue_rows)
        + "\n"
        "---\n"
        "Triage guidance: each candidate should be run through "
        "`repo-agent workflow new-tool --url <...>` before opening a content PR.\n"
    )


# ---------------------------------------------------------------------------
# PR review comment (6.3)
# ---------------------------------------------------------------------------


def render_review_comment(*, pr_number: int, triage_result: dict[str, Any]) -> str:
    labels = triage_result.get("labels") or []
    summary = triage_result.get("summary") or ""
    verdict = triage_result.get("verdict") or "needs-info"
    validation = triage_result.get("validation")
    suggested: list[str] = []
    if verdict == "merge":
        suggested.append("Ready for a human reviewer to sign off.")
    elif verdict == "request-changes":
        suggested.append("Address the hard-gate failures / anti-patterns listed below, then re-request review.")
    elif verdict == "block":
        suggested.append("Entry looks out of scope for this repo — see `ANTI-PATTERNS.md`.")
    else:
        suggested.append(
            "Add the proposed entry inside a ```markdown fenced block in the PR body so the assistant can score it."
        )

    label_line = ", ".join(f"`{l}`" for l in labels) if labels else "_(none)_"
    body_sections = [
        f"{review_marker(pr_number)}",
        "## Rubric review (automated, advisory)",
        "",
        f"**Verdict:** `{verdict}`  ",
        f"**Suggested labels:** {label_line}",
        "",
        f"> {summary}",
        "",
    ]
    if validation:
        body_sections += ["### Scorecard", "", render_scorecard(validation)]
    body_sections += [
        "### Suggested next actions",
        "",
    ]
    body_sections += [f"- {s}" for s in suggested]
    body_sections += [
        "",
        "---",
        "Generated by the Phase 6 `review-pr` workflow. Advisory — a human reviewer always merges. "
        "Add the `skip-review-assistant` label to suppress further updates.",
    ]
    return "\n".join(body_sections) + "\n"
